spring:
  application:
    name: voting
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        column_ordering_strategy: hu.parlament.common.AuditColumnsLastOrderingStrategy
springdoc:
  show-spring-data-rest: false
  paths-to-match: /szavazasok/**
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method